-- Family tree schema, PostgreSQL.
--
-- The same shape as the MySQL version it was ported from, with three
-- differences: identity columns instead of AUTO_INCREMENT, a check
-- constraint instead of ENUM, and a trigger to keep updated_at current.
--
-- There is no changed_at/rebuilt_at here. The old setup wrote data.json to
-- disk and had to track whether the file was stale; this one builds the tree
-- JSON from the database on request, so there is nothing to go stale.

DROP TABLE IF EXISTS children;
DROP TABLE IF EXISTS marriages;
DROP TABLE IF EXISTS people;
DROP TABLE IF EXISTS trees;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS session;

CREATE TABLE trees (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug           varchar(50)  NOT NULL UNIQUE,   -- 'miller', 'horne'
  title          varchar(150) NOT NULL,
  root_person_id integer                          -- set once the first person exists
);

CREATE TABLE people (
  id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tree_id               integer NOT NULL REFERENCES trees (id),
  name                  varchar(150) NOT NULL,   -- no leading asterisk; see adopted
  sex                   varchar(10)  NOT NULL DEFAULT 'unknown'
                          CHECK (sex IN ('man', 'woman', 'unknown')),
  adopted               boolean NOT NULL DEFAULT false,
  is_placeholder        boolean NOT NULL DEFAULT false,

  birth_date_text       varchar(60)  NOT NULL DEFAULT '',
  birth_year            smallint,
  birth_month           smallint,
  birth_day             smallint,
  birthplace_name       varchar(255) NOT NULL DEFAULT '',
  birth_address1        varchar(255) NOT NULL DEFAULT '',
  birth_address2        varchar(255) NOT NULL DEFAULT '',
  birth_city            varchar(255) NOT NULL DEFAULT '',
  birth_state_province  varchar(255) NOT NULL DEFAULT '',
  birth_zip_postal_code varchar(30)  NOT NULL DEFAULT '',
  birth_country         varchar(255) NOT NULL DEFAULT '',
  birth_source          text NOT NULL DEFAULT '',

  death_date_text       varchar(60)  NOT NULL DEFAULT '',
  death_year            smallint,
  death_month           smallint,
  death_day             smallint,
  deathplace_name       varchar(255) NOT NULL DEFAULT '',
  death_address1        varchar(255) NOT NULL DEFAULT '',
  death_address2        varchar(255) NOT NULL DEFAULT '',
  death_city            varchar(255) NOT NULL DEFAULT '',
  death_state_province  varchar(255) NOT NULL DEFAULT '',
  death_zip_postal_code varchar(30)  NOT NULL DEFAULT '',
  death_country         varchar(255) NOT NULL DEFAULT '',
  death_source          text NOT NULL DEFAULT '',

  buried                text NOT NULL DEFAULT '',
  buried_link           varchar(1000) NOT NULL DEFAULT '',
  buried_grave          varchar(1000) NOT NULL DEFAULT '',
  burial_source         text NOT NULL DEFAULT '',
  notes                 text NOT NULL DEFAULT '',
  linked_tree           varchar(50)  NOT NULL DEFAULT '',

  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX people_tree_idx ON people (tree_id);
CREATE INDEX people_name_idx ON people (name);
CREATE INDEX people_birth_year_idx ON people (birth_year);
CREATE INDEX people_death_year_idx ON people (death_year);

ALTER TABLE trees
  ADD CONSTRAINT trees_root_fk FOREIGN KEY (root_person_id) REFERENCES people (id);

-- One row per marriage. person_id is the spouse the chart hangs the marriage
-- under; ordinal orders several marriages for the same person.
CREATE TABLE marriages (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tree_id           integer NOT NULL REFERENCES trees (id),
  person_id         integer NOT NULL REFERENCES people (id),
  spouse_id         integer NOT NULL REFERENCES people (id),
  ordinal           smallint NOT NULL DEFAULT 1,
  married_date_text varchar(60)  NOT NULL DEFAULT '',
  married_year      smallint,
  married_month     smallint,
  married_day       smallint,
  married_place     varchar(255) NOT NULL DEFAULT '',
  married_city      varchar(255) NOT NULL DEFAULT '',
  married_state     varchar(255) NOT NULL DEFAULT '',
  married_source    text NOT NULL DEFAULT '',
  UNIQUE (person_id, ordinal),
  UNIQUE (person_id, spouse_id)
);

CREATE INDEX marriages_tree_idx ON marriages (tree_id);
CREATE INDEX marriages_spouse_idx ON marriages (spouse_id);

-- A person is a child of at most one marriage, so child_id is unique.
CREATE TABLE children (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  marriage_id integer NOT NULL REFERENCES marriages (id) ON DELETE CASCADE,
  child_id    integer NOT NULL UNIQUE REFERENCES people (id),
  position    smallint NOT NULL DEFAULT 0
);

CREATE INDEX children_marriage_idx ON children (marriage_id);

CREATE TABLE users (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      varchar(60)  NOT NULL UNIQUE,
  password_hash varchar(255) NOT NULL,           -- bcrypt
  created_at    timestamptz NOT NULL DEFAULT now(),
  last_login_at timestamptz
);

-- connect-pg-simple keeps sessions here, so a restart doesn't sign you out
CREATE TABLE session (
  sid    varchar NOT NULL COLLATE "default" PRIMARY KEY,
  sess   json NOT NULL,
  expire timestamp(6) NOT NULL
);
CREATE INDEX session_expire_idx ON session (expire);

-- keep updated_at current on people
CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER people_touch BEFORE UPDATE ON people
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();